"""
Decision Twin AI — Career Seed Data.

Curated career catalog used to populate the careers table
and build the FAISS recommendation index.

Based on high-demand career paths relevant to students
across technology, business, science, and creative fields.
"""

from __future__ import annotations

CAREER_SEED_DATA: list[dict] = [
    {
        "title": "Software Engineer",
        "category": "software_engineering",
        "short_description": "Design, build, and maintain software systems at scale.",
        "description": "Software engineers design, develop, test, and maintain software applications and systems. They work across the full stack, from frontend interfaces to backend services, databases, and cloud infrastructure.",
        "median_salary_usd": 120000,
        "salary_range_low": 75000,
        "salary_range_high": 200000,
        "growth_rate_percent": 25.0,
        "automation_risk_percent": 10.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "Python": 7, "JavaScript": 6, "SQL": 6,
            "Git": 7, "Data Structures": 8, "Algorithms": 7,
            "REST APIs": 6, "Problem Solving": 8,
        },
        "preferred_skills": {
            "Docker": 5, "Kubernetes": 4, "AWS": 5,
            "TypeScript": 5, "CI/CD": 5, "System Design": 6,
        },
        "work_environment": "Hybrid/Remote",
    },
    {
        "title": "Data Scientist",
        "category": "data_science",
        "short_description": "Extract insights from data using ML and statistical analysis.",
        "description": "Data scientists analyze large datasets to identify patterns, build predictive models, and drive data-informed decisions across organizations.",
        "median_salary_usd": 130000,
        "salary_range_low": 85000,
        "salary_range_high": 220000,
        "growth_rate_percent": 35.0,
        "automation_risk_percent": 8.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Master's degree preferred",
        "typical_experience_years": 2,
        "required_skills": {
            "Python": 8, "Statistics": 8, "Machine Learning": 7,
            "SQL": 7, "Data Visualization": 6, "Linear Algebra": 6,
        },
        "preferred_skills": {
            "Deep Learning": 6, "NLP": 5, "Spark": 5,
            "R": 4, "Tableau": 4, "A/B Testing": 5,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "Product Manager",
        "category": "product_management",
        "short_description": "Define product strategy and drive execution from concept to launch.",
        "description": "Product managers own the product vision, define requirements, prioritize features, and work cross-functionally with engineering, design, and marketing teams to deliver products that solve user problems.",
        "median_salary_usd": 140000,
        "salary_range_low": 90000,
        "salary_range_high": 200000,
        "growth_rate_percent": 12.0,
        "automation_risk_percent": 5.0,
        "market_demand": "high",
        "job_outlook": "Faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 3,
        "required_skills": {
            "Product Strategy": 8, "User Research": 7,
            "Data Analysis": 6, "Communication": 8,
            "Project Management": 7, "Stakeholder Management": 7,
        },
        "preferred_skills": {
            "SQL": 4, "A/B Testing": 5, "Agile": 6,
            "Wireframing": 4, "Market Analysis": 5,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "UX/UI Designer",
        "category": "design",
        "short_description": "Create intuitive, beautiful user experiences and interfaces.",
        "description": "UX/UI designers research user needs, create wireframes and prototypes, and design visually compelling interfaces that are easy and enjoyable to use.",
        "median_salary_usd": 95000,
        "salary_range_low": 60000,
        "salary_range_high": 150000,
        "growth_rate_percent": 16.0,
        "automation_risk_percent": 12.0,
        "market_demand": "medium",
        "job_outlook": "Faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "Figma": 8, "User Research": 7, "Prototyping": 7,
            "Visual Design": 8, "Information Architecture": 6,
            "Usability Testing": 6,
        },
        "preferred_skills": {
            "HTML/CSS": 5, "Design Systems": 6,
            "Motion Design": 4, "Accessibility": 5,
        },
        "work_environment": "Hybrid/Remote",
    },
    {
        "title": "DevOps Engineer",
        "category": "software_engineering",
        "short_description": "Build and manage CI/CD pipelines, infrastructure, and deployment systems.",
        "description": "DevOps engineers bridge development and operations, automating build/deploy pipelines, managing cloud infrastructure, and ensuring system reliability and scalability.",
        "median_salary_usd": 125000,
        "salary_range_low": 80000,
        "salary_range_high": 185000,
        "growth_rate_percent": 22.0,
        "automation_risk_percent": 15.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 3,
        "required_skills": {
            "Linux": 8, "Docker": 7, "Kubernetes": 7,
            "CI/CD": 8, "AWS": 7, "Terraform": 6,
            "Python": 5, "Bash": 7,
        },
        "preferred_skills": {
            "Ansible": 5, "Prometheus": 5, "Grafana": 4,
            "GCP": 5, "Azure": 5, "Helm": 5,
        },
        "work_environment": "Remote",
    },
    {
        "title": "Machine Learning Engineer",
        "category": "data_science",
        "short_description": "Build and deploy ML models into production systems.",
        "description": "ML engineers design, train, and deploy machine learning models at scale. They bridge the gap between data science research and production engineering.",
        "median_salary_usd": 150000,
        "salary_range_low": 100000,
        "salary_range_high": 250000,
        "growth_rate_percent": 40.0,
        "automation_risk_percent": 5.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Master's degree preferred",
        "typical_experience_years": 3,
        "required_skills": {
            "Python": 9, "Machine Learning": 8, "Deep Learning": 7,
            "PyTorch": 7, "MLOps": 6, "Docker": 6,
            "Mathematics": 7, "Data Engineering": 6,
        },
        "preferred_skills": {
            "Kubernetes": 5, "Spark": 5, "TensorFlow": 6,
            "Hugging Face": 5, "Model Optimization": 6,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "Cybersecurity Analyst",
        "category": "engineering",
        "short_description": "Protect organizations from cyber threats and vulnerabilities.",
        "description": "Cybersecurity analysts monitor, detect, and respond to security threats. They implement security measures, conduct vulnerability assessments, and ensure compliance with security standards.",
        "median_salary_usd": 105000,
        "salary_range_low": 65000,
        "salary_range_high": 165000,
        "growth_rate_percent": 32.0,
        "automation_risk_percent": 8.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "Network Security": 8, "SIEM": 7, "Incident Response": 7,
            "Linux": 7, "Python": 5, "Risk Assessment": 7,
        },
        "preferred_skills": {
            "Penetration Testing": 6, "Cloud Security": 6,
            "Forensics": 5, "Compliance": 5,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "Data Engineer",
        "category": "data_science",
        "short_description": "Design and build data pipelines and warehouse infrastructure.",
        "description": "Data engineers build and maintain the infrastructure that allows data to flow from various sources into data warehouses and analytics systems.",
        "median_salary_usd": 125000,
        "salary_range_low": 80000,
        "salary_range_high": 190000,
        "growth_rate_percent": 28.0,
        "automation_risk_percent": 12.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "Python": 7, "SQL": 9, "Spark": 7,
            "Airflow": 6, "Data Modeling": 7, "ETL": 7,
        },
        "preferred_skills": {
            "Kafka": 6, "dbt": 5, "Snowflake": 5,
            "AWS": 5, "Databricks": 5,
        },
        "work_environment": "Remote/Hybrid",
    },
    {
        "title": "Cloud Solutions Architect",
        "category": "engineering",
        "short_description": "Design scalable, secure cloud infrastructure solutions.",
        "description": "Cloud architects design and implement cloud computing strategies, selecting services, ensuring security, optimizing costs, and creating resilient multi-region architectures.",
        "median_salary_usd": 155000,
        "salary_range_low": 110000,
        "salary_range_high": 230000,
        "growth_rate_percent": 20.0,
        "automation_risk_percent": 7.0,
        "market_demand": "high",
        "job_outlook": "Faster than average",
        "required_education": "Bachelor's degree + certifications",
        "typical_experience_years": 5,
        "required_skills": {
            "AWS": 8, "System Design": 8, "Networking": 7,
            "Security": 7, "Terraform": 7, "Docker": 6,
        },
        "preferred_skills": {
            "GCP": 6, "Azure": 6, "Kubernetes": 7,
            "Cost Optimization": 6, "Compliance": 5,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "Financial Analyst",
        "category": "finance",
        "short_description": "Analyze financial data and guide investment decisions.",
        "description": "Financial analysts evaluate financial data, prepare reports, and make recommendations for business investment decisions, budgeting, and financial strategy.",
        "median_salary_usd": 85000,
        "salary_range_low": 55000,
        "salary_range_high": 140000,
        "growth_rate_percent": 9.0,
        "automation_risk_percent": 25.0,
        "market_demand": "medium",
        "job_outlook": "Average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 1,
        "required_skills": {
            "Financial Modeling": 8, "Excel": 8, "Data Analysis": 7,
            "Accounting": 6, "Presentation": 7, "Critical Thinking": 7,
        },
        "preferred_skills": {
            "Python": 4, "SQL": 4, "Tableau": 5,
            "CFA": 5, "Bloomberg Terminal": 4,
        },
        "work_environment": "On-site/Hybrid",
    },
    {
        "title": "Management Consultant",
        "category": "consulting",
        "short_description": "Advise organizations on strategy, operations, and growth.",
        "description": "Management consultants help organizations improve performance by analyzing business problems, developing strategies, and implementing solutions across operations, technology, and organizational design.",
        "median_salary_usd": 100000,
        "salary_range_low": 65000,
        "salary_range_high": 180000,
        "growth_rate_percent": 11.0,
        "automation_risk_percent": 15.0,
        "market_demand": "medium",
        "job_outlook": "Faster than average",
        "required_education": "Bachelor's degree (MBA preferred)",
        "typical_experience_years": 2,
        "required_skills": {
            "Problem Solving": 9, "Communication": 8,
            "Data Analysis": 7, "Presentation": 8,
            "Strategic Thinking": 8, "Project Management": 7,
        },
        "preferred_skills": {
            "Excel": 6, "PowerPoint": 6, "SQL": 4,
            "Industry Expertise": 5, "Change Management": 5,
        },
        "work_environment": "On-site/Travel",
    },
    {
        "title": "Digital Marketing Manager",
        "category": "marketing",
        "short_description": "Drive growth through digital channels, analytics, and campaigns.",
        "description": "Digital marketing managers plan and execute online marketing strategies across SEO, SEM, social media, email, and content marketing, using analytics to optimize ROI.",
        "median_salary_usd": 80000,
        "salary_range_low": 50000,
        "salary_range_high": 130000,
        "growth_rate_percent": 10.0,
        "automation_risk_percent": 20.0,
        "market_demand": "medium",
        "job_outlook": "Average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "SEO": 7, "Google Analytics": 7, "Content Strategy": 7,
            "Social Media": 7, "Email Marketing": 6, "A/B Testing": 6,
        },
        "preferred_skills": {
            "Google Ads": 6, "Facebook Ads": 5, "Copywriting": 6,
            "Marketing Automation": 5, "Data Analysis": 5,
        },
        "work_environment": "Remote/Hybrid",
    },
    {
        "title": "AI Research Scientist",
        "category": "research",
        "short_description": "Advance the frontiers of artificial intelligence through research.",
        "description": "AI research scientists conduct cutting-edge research in machine learning, NLP, computer vision, and other AI domains, publishing papers and developing novel algorithms.",
        "median_salary_usd": 170000,
        "salary_range_low": 120000,
        "salary_range_high": 300000,
        "growth_rate_percent": 45.0,
        "automation_risk_percent": 3.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "PhD preferred",
        "typical_experience_years": 4,
        "required_skills": {
            "Deep Learning": 9, "Mathematics": 9, "Python": 8,
            "Research Methodology": 8, "PyTorch": 8,
            "Scientific Writing": 7,
        },
        "preferred_skills": {
            "NLP": 7, "Computer Vision": 7, "Reinforcement Learning": 6,
            "JAX": 5, "Publishing": 6,
        },
        "work_environment": "Hybrid",
    },
    {
        "title": "Mobile App Developer",
        "category": "software_engineering",
        "short_description": "Build native and cross-platform mobile applications.",
        "description": "Mobile developers create applications for iOS and Android platforms, working with native frameworks or cross-platform tools to deliver performant, user-friendly mobile experiences.",
        "median_salary_usd": 110000,
        "salary_range_low": 70000,
        "salary_range_high": 175000,
        "growth_rate_percent": 22.0,
        "automation_risk_percent": 12.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "React Native": 7, "JavaScript": 7, "TypeScript": 6,
            "iOS": 6, "Android": 6, "REST APIs": 7,
        },
        "preferred_skills": {
            "Swift": 6, "Kotlin": 6, "Flutter": 5,
            "Firebase": 5, "App Store Optimization": 4,
        },
        "work_environment": "Remote/Hybrid",
    },
    {
        "title": "Biomedical Engineer",
        "category": "healthcare",
        "short_description": "Design medical devices and healthcare technology solutions.",
        "description": "Biomedical engineers combine engineering principles with medical sciences to design devices, software, and systems used in healthcare, from prosthetics to diagnostic equipment.",
        "median_salary_usd": 95000,
        "salary_range_low": 60000,
        "salary_range_high": 145000,
        "growth_rate_percent": 7.0,
        "automation_risk_percent": 15.0,
        "market_demand": "medium",
        "job_outlook": "Average",
        "required_education": "Bachelor's or Master's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "Medical Devices": 7, "Biomechanics": 7,
            "MATLAB": 6, "Regulatory Compliance": 6,
            "CAD": 7, "Research": 6,
        },
        "preferred_skills": {
            "Python": 4, "Signal Processing": 5,
            "3D Printing": 4, "FDA Regulations": 6,
        },
        "work_environment": "On-site/Lab",
    },
    {
        "title": "Full Stack Developer",
        "category": "software_engineering",
        "short_description": "Build end-to-end web applications from frontend to backend.",
        "description": "Full stack developers work across the entire web technology stack, building both client-side and server-side components, managing databases, and deploying applications.",
        "median_salary_usd": 115000,
        "salary_range_low": 72000,
        "salary_range_high": 180000,
        "growth_rate_percent": 25.0,
        "automation_risk_percent": 10.0,
        "market_demand": "high",
        "job_outlook": "Much faster than average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 2,
        "required_skills": {
            "JavaScript": 8, "React": 7, "Node.js": 7,
            "SQL": 7, "HTML/CSS": 7, "Git": 7,
        },
        "preferred_skills": {
            "TypeScript": 6, "Docker": 5, "AWS": 5,
            "GraphQL": 5, "Redis": 4,
        },
        "work_environment": "Remote/Hybrid",
    },
    {
        "title": "Quantitative Analyst",
        "category": "finance",
        "short_description": "Apply mathematical models to financial markets and risk management.",
        "description": "Quants develop mathematical models for pricing derivatives, managing risk, and building algorithmic trading strategies, combining advanced math with programming.",
        "median_salary_usd": 160000,
        "salary_range_low": 100000,
        "salary_range_high": 300000,
        "growth_rate_percent": 15.0,
        "automation_risk_percent": 10.0,
        "market_demand": "medium",
        "job_outlook": "Faster than average",
        "required_education": "Master's or PhD",
        "typical_experience_years": 2,
        "required_skills": {
            "Python": 8, "Mathematics": 9, "Statistics": 8,
            "Stochastic Calculus": 7, "C++": 6, "Financial Modeling": 7,
        },
        "preferred_skills": {
            "Machine Learning": 6, "R": 5, "Bloomberg": 4,
            "Risk Management": 6,
        },
        "work_environment": "On-site",
    },
    {
        "title": "Technical Writer",
        "category": "education",
        "short_description": "Create clear documentation for technical products and APIs.",
        "description": "Technical writers create documentation, guides, and tutorials that help users understand and use software products, APIs, and technical systems effectively.",
        "median_salary_usd": 78000,
        "salary_range_low": 50000,
        "salary_range_high": 115000,
        "growth_rate_percent": 7.0,
        "automation_risk_percent": 30.0,
        "market_demand": "medium",
        "job_outlook": "Average",
        "required_education": "Bachelor's degree",
        "typical_experience_years": 1,
        "required_skills": {
            "Technical Writing": 9, "Communication": 8,
            "Markdown": 7, "API Documentation": 7,
            "Research": 6, "Editing": 7,
        },
        "preferred_skills": {
            "Git": 4, "HTML": 4, "Docs-as-Code": 5,
            "Information Architecture": 5,
        },
        "work_environment": "Remote",
    },
    {
        "title": "Startup Founder / Entrepreneur",
        "category": "entrepreneurship",
        "short_description": "Build and scale new ventures from idea to product-market fit.",
        "description": "Entrepreneurs identify market opportunities, build products, secure funding, and lead teams to create successful businesses, requiring a blend of technical, business, and leadership skills.",
        "median_salary_usd": 0,
        "salary_range_low": 0,
        "salary_range_high": 500000,
        "growth_rate_percent": 8.0,
        "automation_risk_percent": 2.0,
        "market_demand": "medium",
        "job_outlook": "Stable",
        "required_education": "Varies",
        "typical_experience_years": 3,
        "required_skills": {
            "Leadership": 9, "Problem Solving": 9, "Communication": 8,
            "Strategic Thinking": 8, "Fundraising": 6,
            "Product Development": 7,
        },
        "preferred_skills": {
            "Programming": 5, "Marketing": 5, "Financial Planning": 5,
            "Sales": 6, "Networking": 6,
        },
        "work_environment": "Flexible",
    },
    {
        "title": "Robotics Engineer",
        "category": "engineering",
        "short_description": "Design and program robotic systems and autonomous machines.",
        "description": "Robotics engineers design, build, and program robots and automated systems for manufacturing, healthcare, exploration, and other domains, combining mechanical, electrical, and software engineering.",
        "median_salary_usd": 105000,
        "salary_range_low": 70000,
        "salary_range_high": 160000,
        "growth_rate_percent": 12.0,
        "automation_risk_percent": 5.0,
        "market_demand": "medium",
        "job_outlook": "Faster than average",
        "required_education": "Master's degree preferred",
        "typical_experience_years": 3,
        "required_skills": {
            "ROS": 7, "C++": 7, "Python": 7,
            "Computer Vision": 6, "Control Systems": 7,
            "Embedded Systems": 6,
        },
        "preferred_skills": {
            "Deep Learning": 5, "SLAM": 6, "CAD": 5,
            "Simulation": 5, "Sensor Fusion": 6,
        },
        "work_environment": "On-site/Lab",
    },
]
