"""Initial migration

Revision ID: 86d7e0c72ed9
Revises: 
Create Date: 2026-07-19 12:18:39.568571+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d7e0c72ed9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('behavior_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_behavior_event_type', 'behavior_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_behavior_events_user_id'), 'behavior_events', ['user_id'], unique=False)
    op.create_index('ix_behavior_timestamp', 'behavior_events', ['timestamp'], unique=False)
    op.create_index('ix_behavior_user_type', 'behavior_events', ['user_id', 'event_type'], unique=False)
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('median_salary_usd', sa.Integer(), nullable=True),
    sa.Column('salary_range_low', sa.Integer(), nullable=True),
    sa.Column('salary_range_high', sa.Integer(), nullable=True),
    sa.Column('growth_rate_percent', sa.Float(), nullable=True),
    sa.Column('automation_risk_percent', sa.Float(), nullable=True),
    sa.Column('market_demand', sa.String(length=20), nullable=True),
    sa.Column('job_outlook', sa.String(length=50), nullable=True),
    sa.Column('required_education', sa.String(length=100), nullable=True),
    sa.Column('typical_experience_years', sa.Integer(), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_careers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_environment', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_category'), 'careers', ['category'], unique=False)
    op.create_index('ix_careers_category_active', 'careers', ['category', 'is_active'], unique=False)
    op.create_index('ix_careers_demand', 'careers', ['market_demand'], unique=False)
    op.create_index(op.f('ix_careers_title'), 'careers', ['title'], unique=True)
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interests_category', 'interests', ['category'], unique=False)
    op.create_index(op.f('ix_interests_name'), 'interests', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skills_category', 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=36), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_jti'), 'refresh_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('github_url', sa.String(length=2048), nullable=True),
    sa.Column('portfolio_url', sa.String(length=2048), nullable=True),
    sa.Column('resume_url', sa.String(length=2048), nullable=True),
    sa.Column('current_cgpa', sa.Float(), nullable=True),
    sa.Column('highest_degree', sa.String(length=200), nullable=True),
    sa.Column('current_major', sa.String(length=200), nullable=True),
    sa.Column('current_university', sa.String(length=200), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('career_goal_primary', sa.String(length=200), nullable=True),
    sa.Column('career_goal_secondary', sa.String(length=200), nullable=True),
    sa.Column('preferred_industry', sa.String(length=200), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('preferred_work_style', sa.String(length=50), nullable=True),
    sa.Column('twin_completeness_score', sa.Float(), nullable=False),
    sa.Column('total_skills_count', sa.Integer(), nullable=False),
    sa.Column('total_projects_count', sa.Integer(), nullable=False),
    sa.Column('total_certifications_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_profiles_completeness', 'student_profiles', ['twin_completeness_score'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('academic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('major', sa.String(length=200), nullable=False),
    sa.Column('minor', sa.String(length=200), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('max_cgpa', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('achievements', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_academic_records_degree', 'academic_records', ['degree'], unique=False)
    op.create_index('ix_academic_records_profile', 'academic_records', ['profile_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuing_organization', sa.String(length=200), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('credential_url', sa.String(length=2048), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_certifications_org', 'certifications', ['issuing_organization'], unique=False)
    op.create_index('ix_certifications_profile', 'certifications', ['profile_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('repository_url', sa.String(length=2048), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('impact_description', sa.String(length=5000), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_profile', 'projects', ['profile_id'], unique=False)
    op.create_table('psychometric_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('openness', sa.Float(), nullable=True),
    sa.Column('conscientiousness', sa.Float(), nullable=True),
    sa.Column('extraversion', sa.Float(), nullable=True),
    sa.Column('agreeableness', sa.Float(), nullable=True),
    sa.Column('neuroticism', sa.Float(), nullable=True),
    sa.Column('risk_tolerance', sa.Float(), nullable=True),
    sa.Column('creativity_score', sa.Float(), nullable=True),
    sa.Column('leadership_score', sa.Float(), nullable=True),
    sa.Column('analytical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('raw_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_psychometric_assessed', 'psychometric_assessments', ['assessed_at'], unique=False)
    op.create_index('ix_psychometric_profile', 'psychometric_assessments', ['profile_id'], unique=False)
    op.create_index('ix_psychometric_type', 'psychometric_assessments', ['assessment_type'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'interest_id', name='uq_user_interest')
    )
    op.create_index('ix_user_interests_interest', 'user_interests', ['interest_id'], unique=False)
    op.create_index('ix_user_interests_profile', 'user_interests', ['profile_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index('ix_user_skills_proficiency', 'user_skills', ['proficiency_level'], unique=False)
    op.create_index('ix_user_skills_profile', 'user_skills', ['profile_id'], unique=False)
    op.create_index('ix_user_skills_skill', 'user_skills', ['skill_id'], unique=False)
    op.create_table('course_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academic_record_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['academic_record_id'], ['academic_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_grades_record', 'course_grades', ['academic_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_grades_record', table_name='course_grades')
    op.drop_table('course_grades')
    op.drop_index('ix_user_skills_skill', table_name='user_skills')
    op.drop_index('ix_user_skills_profile', table_name='user_skills')
    op.drop_index('ix_user_skills_proficiency', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index('ix_user_interests_profile', table_name='user_interests')
    op.drop_index('ix_user_interests_interest', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_index('ix_psychometric_type', table_name='psychometric_assessments')
    op.drop_index('ix_psychometric_profile', table_name='psychometric_assessments')
    op.drop_index('ix_psychometric_assessed', table_name='psychometric_assessments')
    op.drop_table('psychometric_assessments')
    op.drop_index('ix_projects_profile', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_certifications_profile', table_name='certifications')
    op.drop_index('ix_certifications_org', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_academic_records_profile', table_name='academic_records')
    op.drop_index('ix_academic_records_degree', table_name='academic_records')
    op.drop_table('academic_records')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index('ix_student_profiles_completeness', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index('ix_skills_category', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_interests_name'), table_name='interests')
    op.drop_index('ix_interests_category', table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_careers_title'), table_name='careers')
    op.drop_index('ix_careers_demand', table_name='careers')
    op.drop_index('ix_careers_category_active', table_name='careers')
    op.drop_index(op.f('ix_careers_category'), table_name='careers')
    op.drop_table('careers')
    op.drop_index('ix_behavior_user_type', table_name='behavior_events')
    op.drop_index('ix_behavior_timestamp', table_name='behavior_events')
    op.drop_index(op.f('ix_behavior_events_user_id'), table_name='behavior_events')
    op.drop_index('ix_behavior_event_type', table_name='behavior_events')
    op.drop_table('behavior_events')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
